Part I The Printing Revolution
We should notice the force, effect, and consequences of inventions, which are nowhere more conspicuous than in those three which were unknown to the ancients; namely, printing, gunpowder, and the compass. For these three have changed the appearance and state of the whole world; first in literature, then in warfare, and lastly in navigation: and innumerable changes have been thence derived, so that no empire, sect, or star, appears to have exercised a greater power and influence on human affairs than these mechanical discoveries.
Francis Bacon, Novum Organum, 1620
1 Printing
The printing revolution bridged the medieval and modern worlds with enormous force, effect, and consequences. Beginning in 1454, printing technology spread quickly over Europe and played a central role in the great sweep of events--the Renaissance, the Protestant Reformation, the Enlightenment, and the political, industrial, and scientific revolutions from the 1600s to the twenty-first century.
Before printing, people were linked through individual and small group communication, within oral and manuscript cultures, in Asian and then European civilizations. The need to replicate these manuscripts first inspired woodblock printing and then moveable type.
After printing, the sudden acceleration of communication had enormous social and political impacts, leading to even greater acceleration and everexpanding horizons. The original printing revolution in Europe was followed by the industrialization of media technologies in the nineteenth century--including the telegraph and steam-powered printing--which created the opportunity for larger audiences and new institutions to serve them.
The resulting newspapers and wire services, said Chicago publisher Joseph Medill, were like proud steam ships, "bidding defiance to the tempests, laden with the mails and commerce of the world" (Brendon 1983). Titanic industrial media institutions of all types continued defying the tempests through the nineteenth and twentieth centuries.
Then, by the early twenty-first century, the proud old steamers of the press began sinking, losing two-thirds of their income and most of their value. In city after city, the empty newsrooms were like ghost ships of the press, no longer bidding defiance to anything but their creditors.
The question is not so much about why they faltered. Centuries from now, historians will probably ask instead: how is it that the cultures and institutions growing out of the printing revolution were able to survive so well for five and a half centuries, from 1455 to the early twenty-first century? What cultures and institutions replaced them, and with what force and effect today?
This section on the Printing Revolution compresses these 550 years of publishing into three chapters in order to take the broadest possible view of media history.
oChapter 1 covers the early printing revolution up to 1814;
oChapter 2 describes the industrial media revolution in the following century; and
oChapter 3 describes the central role and rapid fall of print media in the twentieth century.
However, in order to appreciate the printing revolution, we first need to understand the oral culture and manuscript culture that it replaced.
2 Before the Printing Revolution: Oral Culture
Since the emergence of intelligent humanity, groups of people have communicated within what we call an oral culture. Although records of oral culture don't really emerge until the dawn of writing, recent contact with onceisolated cultures and related psychological research has shown that oral cultures have their own forms of wisdom and integrity.
Research has shown, for instance, that humans are born with a natural capacity for complex language with thousands of words and symbols. Most other species, with some possible exceptions, have little capacity for anything beyond a few basic signals. Studies comparing human and primate language abilities using functional Magnetic Resonance Imaging (fMRI) have shown that the human brain has special segments devoted to language (Wolf 2008).
In other words, we are "pre-wired" to talk and communicate, and for nearly all of our natural history, we have communicated songs, folklore, history, and traditions within oral culture.
Storytelling and oral traditions appear all through the world and all through the ages (Campbell 1949). Storytellers, troubadours, and jongleurs carried songs and stories in cultures where people did not read. While the troubadours were lyric poets who dealt mainly with issues of chivalry and courtly love, the jongleurs were the itinerant singers who memorized these poems using verse and other mnemonic devices. A good jongleur or storyteller could memorize long poems or stories after hearing them only a few times (Burke 1982).
Along with the need for memorization, communication researchers such as Walter Ong have found that oral culture tends to be quite different from the print, visual, electronic, and digital cultures that followed. People in oral cultures think in concrete and practical ways, rather than using modern abstract or linear concepts. For example, familiar objects like a plate, or the moon, might be used to refer to the idea of a circle. Asked about themselves, a person in an oral culture would be reluctant to analyze or put themselves in another person's place (Ong 1982; Lerner 1958).

Figure PI.1 Oral Tradition--Storytelling, as part of traditional oral culture, goes back to the dawn of human existence. In this 1902 painting by E. Irving Couse, a Native American storyteller is recounting events around a battle.
Another attribute of people in oral cultures is that they tend to make decisions by consensus, in groups, rather than within a hierarchy. People in oral cultures tend to have polarized worldviews, oriented towards good and evil. They also tend to have a love of epic sagas and poetry. Storytellers rely heavily on formulas and themes in order to recall these epics through a tradition of improvisation, mnemonic devices, and rote memory. Using these devices, oral cultures can accurately transmit important information from generation to generation.
We tend to underestimate the effectiveness of oral cultures. We're all familiar with the children's game in which a message is whispered from one person to another until it goes around a room. The message invariably gets garbled-- sometimes with hilarious results--when the original message and the final message are compared. But this is misleading. When it is important, oral cultures can accurately transmit information across long distances and through generations. For example, American author Alex Haley was able to discover an oral record of his ancestors in Africa, and his search is described in the 1976 book, Roots: The Saga of an American Family. Similarly, the Odyssey and Iliad were originally heroic oral histories of Greek culture that were only written down many centuries after they were composed.
After the introduction of writing, oral cultures continued to exist alongside manuscript cultures. But oral cultures were considered more reliable, in that messages gained validity through oral delivery. This tradition continues to be important, for example, in the way that legislative proposals are "read" into the record, a sermon is delivered orally in a church, or a lecture is given in a classroom. Similarly, decision by consensus in the modern jury system and the corporate boardroom are vestiges of the consensus orientation of oral cultures.
The move to symbols and then written language profoundly reshaped patterns of human thinking, and it could not have been an easy process. As oral cultures became lost over time, some of the world's most poignant literature emerged in its wake. Examples would include Oliver Goldsmith's 1770 poem, The Deserted Village, which lamented rural communities lost to Britain's enclosure acts; Chinua Achebe's 1958 book, Things Fall Apart, which described the impact of European colonialism on social structures in Africa; and Anne Pancake's 2008 book, Strange as This Weather Has Been, which follows the social disintegration in traditional Appalachian communities created by mountaintop mining. Of course, not everyone takes a sanguine view of traditional oral cultures. "We dream that the country was idyllic in the 18th century, a lost paradise like The Deserted Village," said Jacob Bronowski in his Ascent of Man. "That is a fable. The country was a place where men worked from dawn to dark ... [i]n poverty and darkness" (Bronowski 1976).
One of the reasons radio may have been so successful as a mass medium, according to communications theorist Marshall McLuhan, was that it revived this sense of community, for example through "fireside chats" and radio drama. To McLuhan, this seemed to be a "re-tribalization" of a culture that longed for an older and more community-oriented communications system.
Another link to the old oral culture is the epic fantasy genre in books, games, and cinema, such as Harry Potter or Lord of the Rings. These movies may help recover this sense of connection to the heroic epic that was once served by the oral culture (Drout 2006; Campbell 1949).
3 Before the Printing Revolution: Symbols, Seals and Icons
The earliest known enhancements to oral culture involved symbolic Ice Age carvings from ivory and bone from as long as 45,000 years ago. These are not tools--they are intentionally carved and painted objects that are worn and polished by repeated handling over a long period. They don't seem to be related to the Ice Age cave paintings that flourished in some parts of Europe around the same time (Marshack 2003).
We don't know what role these objects played in the oral cultures in this prehistoric time. We can guess that a carving of a mother goddess may have related to fertility, or a carving of a horse might have involved pre-hunting rituals. It's also possible that the objects had some use within the group decisionmaking process, perhaps being passed around from speaker to speaker to indicate who had the privilege of speaking at a particular moment.
Another class of symbols before printing involved seals and stamps for making impressions on clay, wax, papyrus, or fabrics. The purpose might have been decorative or authoritative, for example, to authenticate a document. Roman historian Marcus Terentius Varro was said to have inserted images of several hundred illustrious persons by the aid of "a certain invention," thus "saving their features from oblivion" and "making them known over the wide world" (Bawker 1887). The invention was probably woodblock printing or some kind of embossing. "As the inventor of a benefit which will fill even the gods with jealousy, he has clothed these persons with immortality," Roman historian Pliny the Elder said cryptically (De Vinne 1877).
Symbolic and visual communication was also embedded in medieval and Renaissance architecture, sculpture, and painting. These iconic images were the news and educational vehicles of the day. People of the twelfth century would visit Chartres Cathedral to learn religious stories in the same way that scholars would flock to Oxford or the Sorbonne and read books in the following centuries.
We will return to this theme in Section II, The Visual Revolution.
4 Before the Printing Revolution: Writing and Manuscript Cultures
Unlike language, writing is not pre-wired in the human brain. It had to be invented, and because of that, we often see writing as the first communications revolution that extended natural human abilities.
The first kinds of writing involved the use of clay tokens dating back to 8500 BCE to ancient Mesopotamia, and possibly just as early in ancient China (Schmandt-Besserat 1996; Rincon 2003). Meant to keep track of resources like grain and animals, these original clay tokens were three-dimensional solid shapes like spheres, cones, and cylinders kept in clay boxes. At some point along the way, the system changed from keeping 100 clay ox tokens to a symbol for the number 100 along with the symbol for ox. Increasing trade led to a further need to simplify accounting, which spurred the development of writing.
Hieroglyphic symbols emerged in Egypt around 3500 BCE, while formal Chinese writing emerged around 1500 to 1200 BCE, although some early primitive writing apparently goes back to 6600 BCE. Olmec, Zapotec, and Mayan writing emerged in Mexico in the 1000 BCE to 300 BCE era.
Like Egyptian hieroglyphs, Chinese and Mayan written languages are logographic, in that they began with representations of familiar objects through a logo or representation of the object. The simplest type of logograms would be direct representations of the object.
Egyptian, Chinese, and Mayan systems were also partially syllabaric systems, in that the written symbols in the more complex forms of the language can represent the syllables that make up different words. Japanese is an example of a syllabaric system.
Another major type of written language is alphabetic, in which individual characters represent phonemes (sounds) of the spoken language. The first alphabetic writing dates back to about 1800 BCE from the Sinai Peninsula, but its elements seem to have been derived from Egyptian hieroglyphs adapted to language. The alphabet was a democratization of writing, and alphabets in the world today are derived from that original Semitic script (Conner 2005).

Figure PI.2 Medieval Storytelling--Wood carving depicting the Adoration of the Magi at Chartres Cathedral exemplifies the use of sacred iconography in oral tradition. Photo by Lin Burton.
4.1 Impact of writing and manuscript cultures
The introduction of writing brought about a change in thinking for previously oral cultures. Historian Walter Ong noted that writing and printing introduced a more linear, sequential and homogeneous approach to thinking, in contrast to the older oral cultures of heroic epics, songs, and tales told by firelight (Ong 2002). Similarly, theorist Walter Benjamin saw mechanical reproduction of writing and art as contributing to a loss of social ritual and personal identity (Benjamin et al. 2008).
Plato famously warned in his dialogue Phaedrus that writing would lead to the loss of memory, which was one of the key elements (canons) of rhetoric:
If men learn this [writing], it will implant forgetfulness in their souls; they will cease to exercise memory because they rely on that which is written ... It is no true wisdom that you offer your disciples, but only its semblance, for by telling them of many things without teaching them, you will make them seem to know much, while for the most part they know nothing, and as men filled, not with wisdom but with the conceit of wisdom, they will be a burden to their fellows.
Although specialized messengers could be trained to remember complex messages to be carried over time and distance, scribes with flexible media could more easily speed messages through empires, and this was vital to their success, according to historian Harold Innis.
Types of Written Language
Logographic: In which the Egyptian hieroglyph is a duck, and the Chinese logogram ? stands for mountain.
Syllabaric: In which certain symbols stand for syllables. Complex logographic systems like Chinese, or those derived from logographic systems (like Japanese), have characters that stand for syllables.
Alphabetic: Where individual characters stand for phonemes (sounds) of the spoken langage. For instance, English is based on the Latin alphabet (A, B, C, D ...); Russian is based on the Cyrillic script ( A, B, ?, ?, ...).
An important point about these forms of written language is that alphabets can communicate billions of ideas with only about two dozen symbols. In contrast, logographic and syllabaric systems require thousands of symbols. This is not a problem in a manuscript culture, but it was a crucial difference in the development of mass communication through printing, since it is difficult to create and organize thousands of separate permanent symbols to be used in a printing press. So, for example, even though Bi Sheng invented printing with moveable ceramic type in China in 1041-8--about 500 years before Johannes Gutenberg used metal type--the system was too cumbersome to be entirely useful, and Chinese printers continued to use carved wooden blocks until the modern era.
Writing grew naturally from the elite, in early cultures, to the upper and then middle classes in the Greek and Roman empires. Literacy faded in Europe during the early medieval period, around 500-1000 CE, when reading and writing were almost exclusively the province of the clergy. Charlemagne, Frederic Barbarosa, most popes, and most kings and queens of the period were not even able to sign their names. Writing was held in such contempt that when the Crusaders took Constantinople in 1204, "they exposed to public ridicule the pens and ink stands that they found in the conquered city as the ignoble arms of a contemptible race of students" (De Vinne 1877).
At the same time, literacy was nearly universal in other cultures, for example, in Arab nations in the 900-1500 period when great centers of learning flourished from Timbuktu, Mali, to Baghdad, Iraq. Many of the great literary treasures of Greek and Roman civilizations were saved by the literate Arab culture of this era, and appreciated once again in Renaissance Europe only after around 1200-
1300 CE.
Writing, said media scholar Wilbur Schramm, is what allowed humans to conserve intellectual resources, to preserve the legacy without having to keep all the details in their heads, and to devote energy to advancing knowledge. This had an enormous effect on human life. "With language and writing in hand, humans had paid the tuition for their own education," Schramm said. Mass media, beginning with the printing revolution, would become their open university.

Figure PI.3: Manuscript Culture--A monk works on a manuscript in this mural from the "Evolution of the
Book" located at the Library of Congress in Washington, DC. Mural by John W. Alexander, 1896. Photo by Carol Highsmith, Library of Congress.
Technologies of Writing
Along with language, written communication may require four basic items: an instrument, a carrier (medium), a vehicle, and a way to prepare the vehicle. In Chinese traditional culture these are called the "Four Treasures of the Study," and the specific examples are the brush, the paper, the ink, and the ink-stone.
The earliest civilizations tended to use durable materials, such as clay and stone, to keep track of accounts and send messages through long durations of time.
Stone is the most durable medium but not at all flexible. Carvings and paintings on stone are found throughout the ages, in all parts of the world, as permanent records of empires and faiths. The bestknown example is the Rosetta Stone, a decree involving an Egyptian king's divinity, carved on a granite-like rock in 196 BCE and discovered in 1799 by Pierre-Francois Bouchard, a soldier who was part of the Napoleonic expedition to Egypt. Because the decree was carved in three languages-- Hieroglyphic, late Egyptian (Demotic), and ancient Greek--it opened the door for the translation of hieroglyphics.
Clay was the simplest and earliest writing medium. Between half a million and two million clay tablets and markers from ancient Mesopotamia have been recovered in the modern era. Scribes once used a wedge-shaped stylus to make marks in clay, which was then fired in kilns to create a permanent record; or the clay could be recycled for reuse later if the record was not permanent. Early Mesopotamian writing is called Cuneiform, which is Latin for "wedge shaped." Cuneiform translation began in 1835 when Henry Rawlinson visited an archeological site in what is now eastern Iran to see the Bisotun (or Behistun) inscriptions. He realized that, like the Rosetta Stone, the inscriptions consisted of three identical texts.
Papyrus is a plant native to the wetlands of the Nile valley of Egypt. It was originally used by the classical civilizations of Egypt, Greece, and Rome. It is pounded flat and laid crossways to create a sheet of papyrus paper, and is effective because the plant has a glue-like material that holds the sheet together. The first examples are from about 2550 BCE.
Wax tablets on a wooden backing were often used in ancient Greece and Rome for writing that was temporary. Two tablets could be hinged together to protect the wax, which is an idea that probably led to the codex (book).
Parchment was a widely used medium in the ancient Roman Empire that employed the skin of sheep, goats, cows, or other animals. Unlike leather, which is tanned, parchment membranes are soaked and scraped thin to provide a high quality writing surface. The best parchment was vellum, usually from calfskin.
Silk was used since at least the second century BCE in China for transmitting and preserving important religious and civil texts. Silk was flexible but very expensive, and its use was highly restricted to royalty.
Paper is traditionally said to have been discovered by Ts'ai Lun, a Chinese monk who observed paper wasps making a nest around 105 CE. The technique is a huge improvement over hard-toprepare animal hides, brittle papyrus, and expensive silk. Finely chopped wood or rag fibers are mixed with glue in a vat, and then poured over a screen. The thin layer of fibers on the screen dries into paper. Cheap paper became widely available around 1400 in Europe and was apparently in surplus by the mid-1400s. One contributing factor may have been the increased number of linen rags from cast-off clothing, which people needed to weather the winters in the Little Ice Age (c. 1315-1800).
Figure PI.4 Parchment--Scraping and smoothing animal skins is part of the ancient process of preparing parchment, a long-lasting but expensive medium. Woodcut by Jost Amman (1539-91) from "True Description of all Professions on Earth, exalted and humble, spiritual and worldly," 1568.
