After the hard rain on the way to the beach, and wading out chest-deep to the skiffs, everyone was drenched. It was still dark out when the two Indonesian crew members pulled back the tarp they had nailed over our heads. The coast was a vague shadow growing vaguer. The Indonesians distributed life vests: ridiculous things, made from thin fabric and a bit of foam. The youngest children, including a girl in a pink poncho who appeared no older than 4 or 5, were directed with their parents to a small square of open deck in the stern. The reason for this was that the farther aft you went, the less violent was the bucking as we plowed into the swells.
As the sun broke, we got our first good look at one another. Rashid had made it, as well as several other men from the tower block. There were nine children and more than a dozen women. Aside from one Afghan man, from Kunduz Province, everyone was Iranian. Most of the elderly crowded into the covered bow or leaned against the bulwarks. The rest fit where they could on the open deck. The sea was choppy enough so that each time the boat crashed from a peak into a trough or hit a wave head-on, large amounts of water splashed against us.
The first person to become sick was Siya. It was still early morning when he started throwing up. He was a natural leader, that man, and almost everyone soon followed suit. By late afternoon, we’d lost sight of land completely, and the swells grew to a size that blocked out the horizon when they loomed above us. Some people bent over the gunwales, some vomited into plastic bags. It quickly became apparent that there were not enough bags to go around: rather than toss them overboard, full ones had to be emptied, rinsed and reused.
Siya would not be cowed. Peeling off his soaking tank top, revealing his tattooed wings — seeming to unfold them, actually, as he threw back his shoulders — he began to sing. Others joined in, breaking now and then to retch.
It was slow going. The Indonesians took turns manning the tiller and hand-pumping water from the bilge. One was older and taciturn and wore a permanent scowl; the other looked to be in his teens, smiled enough for the both of them and called everybody “brother.” The tremendous racket of the engine belied its less-than-tremendous horsepower. Like the rest of the vessel, it was built for neither such a heavy load nor such high seas. Our typical speed was four to five knots, less than six miles per hour, and at times we seemed to make no headway whatsoever against the strong southeasterly trade winds, which whipped up white caps on the waves and kept us all alert with stinging gusts of spray. Depending on the direction of the swells, the Indonesians would signal the men to consolidate themselves on the starboard or port side of the deck and thereby mitigate our listing — which, now and then, felt alarming.
The sea was still big when the sun went down, taking with it the warmth. Those of us who had spent the day on our feet now began staking claims on places to try to sleep. The deck became a claustrophobic scrum of tangled limbs. Few could recline or stretch their legs. Each time someone tried to reposition a foot or knee, say, to restore some circulation, the movement would ripple out in a cascade of shifting and grumbling as the surrounding bodies adjusted to the new configuration.
The tarp was unfurled. There was not enough of it to cover everyone. If you found yourself on an edge or corner, someone from the opposite side would invariably pull it away the moment you relaxed your grip. In any case, it was too worn and porous to do much. The water ran down its folds and creases, streaming through the many tears along the way.
In the morning, everyone looked different. Sallow. Haggard. Reduced. Amir and Sami slouched limply against each other, passing between them a bulging plastic bag. The man with the faux-hawk was curled up in a fetal ball: he stayed that way the rest of the trip. His pregnant wife sat cross-legged near the bow, pale and wet and trembling. Rima was clutching Siya’s arm, as if it were a lifeline. Their eyes were squeezed tightly shut, but they were too ill to sleep.
Another problem arose. There was no toilet, and absent any railing to hold on to, going over the side was too risky. The men urinated on the hull, the women in their pants.
The Indonesians had brought a box of sealed plastic cups of water, but hardly anyone could hold them down. Siya continued to sing and puke. Although a couple of the children had begun to cry, none complained. In the afternoon, two dolphins appeared and spent the better part of an hour playfully showing off. As they darted under the boat, and launched into the air, the spectacle cheered up everyone, adults and kids alike. Even Amir and Sami rallied from their stupor to watch. A few grown men became positively gleeful, vying to be the first to spot the gray shadows flitting from the deep.
That night, several of us tried to sleep atop the engine room, trading the shelter of the hull for a little extra space. It was a poor call. Every 10 minutes or so, a bucket’s worth of cold water took your breath away or you were pitched against a hot pair of vertical pipes spewing noxious smoke and sparks. There was nothing to do but lie there, bracing for one or the other, admiring the magnificent array of stars and the phosphorescence glowing in the wake.
With first light, despite the sleep deprivation, dehydration, seasickness and filth, the asylum seekers were energized by the fact that, according to the Indonesians, we would likely reach Australian territory before nightfall. Although there was still no land in sight, the arrival of birds circling overhead was unanimously interpreted as a sign that we were getting close. The sea had also calmed: no more waves crashed upon the deck. Initially, this was an enormous relief. For the first time, the sun dried us out. As it crept higher, however, it proved to be far more powerful than during the past two days, and soon, without a single cloud in the sky to blunt the blistering rays, everyone was longing for the same frigid breakers we previously cursed.
. . .
Presently, the heat finished off anyone who might have been bearing up. The pregnant woman’s condition bordered on critical. She was flushed and drenched in sweat and heaved dryly, with nothing left to give. Sami was weeping. Amir lay supine. His eyes drooped catatonically, and when I tried to make him drink some water, he weakly gripped my ankle.
“I need help,” he said. “Call for help.”
That decision seemed to be up to Siya. There was a satellite phone onboard: Siya said the plan was to contact the Australian authorities once we were well within their waters. The navy would then bring us ashore. In the past, asylum boats often made it all the way — but the landing can be treacherous (when one boat smashed on the cliffs in 2010, 50 people drowned), and now it’s standard practice to request a “rescue” before reaching Christmas Island. Although Australian rescuers, when responding to distress calls, venture much farther north than where we currently were, Siya wanted to be sure. I think it was Amir’s pitiful entreaties that finally persuaded him to make the call.
An Iranian man who knew some English — the one who in Jakarta told me he was an engineer — spoke to the dispatch. The Indonesians had brought a hand-held G.P.S. device; neither they nor the asylum seekers, however, knew how to work it. Eventually, someone offered his iPhone, and the engineer read out our coordinates.
While we waited to be rescued, the Iranians set about destroying their passports. “So they can’t deport you,” Farah told me. Clearly, though, the task also carried some symbolic weight. Rather than simply jettisoning them, the asylum seekers painstakingly ripped out each individual page, crumpled it into a ball, and tossed it to the wind. A pair of scissors was passed around. The burgundy covers, emblazoned with the Iranian coat of arms, were cut into tiny pieces. The work was accomplished with flair and relish. Only one man seemed hesitant. Moving closer, I saw that the passport he was disposing of was his son’s. When the scissors came his way, he carefully cut out the photo on the first page and slipped it in his wallet.
Soon, on the horizon, a ship appeared. A government airplane buzzed above us, swooped low and made a second pass. The asylum seekers waved shirts in the air, crying out in jubilation. The younger Indonesian performed a dance atop the engine room; he seemed amazed we had made it. Some of the men emptied their pockets, thrusting on him all the cash they had. The Indonesian beamed. “Thank you, brothers!”
Two skiffs broke off from the battleship and motored our way. Each carried six Australians in gray fatigues, riot helmets and sidearms holstered on their thighs. The Indonesians cut the engine (and after three days of its unrelenting clamor, the silence that replaced it was startling). The skiffs maneuvered abreast of us, one on each side.
The Australian sailors all looked like fresh recruits. One of them held a manual of some kind. He read from it in a loud voice. “Are there any English speakers?”
The engineer stepped forward.
“Does anyone onboard require medical assistance?”
When the engineer translated this, nearly everyone raised his hand. The pregnant woman was helped to her feet and presented. Her head hung heavily. She was almost too weak to stand.
While the Australian with the manual recited more questions — including some in Indonesian addressed to the crew, who shook their heads dumbly, refusing to answer — his fellow sailors passed to the asylum seekers new life vests, a couple jerrycans of fresh water, some bags of frozen tortillas, bottles of honey and a tub of strawberry jam. “We’re going back to the ship now,” one of them told the engineer. “You have to turn the engine back on and keep going. We’ll be behind you.”
. . .
There was nothing to do but heed the Australian’s command and “keep going.” It was four or five hours after we made contact with the first ship when a second, smaller patrol boat materialized. Two more skiffs of sailors came out to meet us. This time they immediately boarded the boat, moving people aside, herding everyone forward. The officer in charge announced that he was taking control of the vessel.
After the officer spotted Joel’s camera, we were both summoned to the stern, at which point we identified ourselves as journalists. While a big Australian with a bushy beard worked the tiller, the officer went through a list of prewritten questions with the crew, each of whom either couldn’t read or declined to. (Unless it’s their second offense, or someone dies, the Indonesian fishermen who bring asylum boats across are often not prosecuted.) The officer was polite to Joel and me. He said we had been lucky with the weather. If we had left a few days earlier, the boat would have capsized.

